# A list of file extensions that nanoc will consider to be textual rather than
# binary. If an item with an extension not in this list is found,  the file
# will be considered as binary.
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'txt', 'xhtml', 'xml' ]

# The path to the directory where all generated files will be written to. This
# can be an absolute path starting with a slash, but it can also be path
# relative to the site directory.
output_dir: output

# A list of index filenames, i.e. names of files that will be served by a web
# server when a directory is requested. Usually, index files are named
# “index.hml”, but depending on the web server, this may be something else,
# such as “default.htm”. This list is used by nanoc to generate pretty URLs.
index_filenames: [ 'index.html' ]

# Whether or not to generate a diff of the compiled content when compiling a
# site. The diff will contain the differences between the compiled content
# before and after the last site compilation.
enable_output_diff: false

# The data sources where nanoc loads its data from. This is an array of
# hashes; each array element represents a single data source. By default,
# there is only a single data source that reads data from the “content/” and
# “layout/” directories in the site directory.
data_sources:
  -
    # The type is the identifier of the data source. By default, this will be
    # `filesystem_unified`.
    type: filesystem_unified

    # The path where items should be mounted (comparable to mount points in
    # Unix-like systems). This is “/” by default, meaning that items will have
    # “/” prefixed to their identifiers. If the items root were “/en/”
    # instead, an item at content/about.html would have an identifier of
    # “/en/about/” instead of just “/about/”.
    items_root: /

    # The path where layouts should be mounted. The layouts root behaves the
    # same as the items root, but applies to layouts rather than items.
    layouts_root: /

deploy:
  default:
    dst: "sherman:/srv/www/redisbook.org/public_html"

book:
  title: "The Redis Book"
  head: |-
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="/svg/svg.js"></script>
    <meta name="viewport" content="width=880" />
  header_links: |-
    <li><a href="http://github.com/peterc/redisbook">GitHub</a></li>
  footer: |-
    <div style="font-size: 0.8em; line-height: 1.4em; color: #666"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0; margin-top: 6px" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br />Copyright &copy; 2010 Peter Cooper</div>
  theme_color: "#d20"
  alt_color: "#356938"
  text_color: "#111"
  link_color: "#04c"
  pale_color: "#bbb"
  body_classes: 
  header_fonts: "\"Museo Slab\", \"Myriad Pro\", \"Helvetica Neue\", Helvetica, Arial, sans-serif"
  body_fonts: "Georgia, Palatino, Times, \"Times New Roman\", serif"
  monospace_fonts: "Menlo, Monaco, \"Liberation Mono\", \"Droid Sans Mono\", Courier, monospace"
    